#!/bin/sh

clear

if [ $EUID != 0 ]
then
    source $HOME/.dotfiles/formatting_vars
    echo -e "${ESC_CHAR}${BOLD}$(($RED))${END}You must run this as root"
    exit
fi

echo "Here are the supported distros:"
echo "  1. Arch-based"
echo "  2. Fedora"
read -p "Select which you are using: " environment
if [[ $environment != '1' && $environment != '2' ]]; then
    echo "Invalid input: exiting..."
    exit
fi
if [[ $environment == '1' ]]; then
    echo "arch"
    source /home/$SUDO_USER/.dotfiles/install_packages_arch
elif [[ $environment == '2' ]]; then
    source /home/$SUDO_USER/.dotfiles/install_packages_fedora
fi

echo "Here are the supported environments:"
echo "  1. Hyprland"
echo "  2. KDE Plasma"
read -p "Select which you are using: " environment
if [[ $environment != '1' && $environment != '2' ]]; then
    echo "Invalid input: exiting..."
    exit
fi

clear
read -p "Install packages? [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    install_base_packages
    install_environment_packages $environment
fi

clear
read -p "Install config files [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    sudo -u $SUDO_USER mkdir /home/$SUDO_USER/.config
    sudo -u $SUDO_USER cp -rf /home/$SUDO_USER/.dotfiles/configs/general/* /home/$SUDO_USER/.config
    sudo -u $SUDO_USER cp -rf /home/$SUDO_USER/.dotfiles/Pictures/* /home/$SUDO_USER/Pictures
    if [[ $environment == '1' ]]; then
        sudo -u $SUDO_USER cp -rf /home/$SUDO_USER/.dotfiles/configs/hyprland/* /home/$SUDO_USER/.config
    elif [[ $environment == '2' ]]; then
        sudo -u $SUDO_USER cp -rf /home/$SUDO_USER/.dotfiles/configs/kde/* /home/$SUDO_USER/.config
    fi
fi

clear
read -p "Install grub theme [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    /home/$SUDO_USER/.dotfiles/configs/grub/install
fi

clear
read -p "Install sddm theme [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    install_sddm_packages
    /home/$SUDO_USER/.dotfiles/configs/sddm/install
fi

clear
read -p "Install yay? [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    sudo -u $SUDO_USER git clone https://aur.archlinux.org/yay.git /home/$SUDO_USER/yay
    (cd /home/$SUDO_USER/yay && sudo -u $SUDO_USER makepkg -si)
    rm -rf /home/$SUDO_USER/yay
fi

clear
read -p "Install zsh? [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    install_zsh
    
    sudo -u $SUDO_USER chsh -s /bin/zsh

    sudo -u $SUDO_USER cp -f /home/$SUDO_USER/.dotfiles/configs/.zshrc /home/$SUDO_USER/.zshrc
    sudo -u $SUDO_USER cp -f /home/$SUDO_USER/.dotfiles/configs/.zshenv /home/$SUDO_USER/.zshenv

    sudo -u $SUDO_USER git clone https://github.com/zsh-users/zsh-autosuggestions /home/$SUDO_USER/.zsh/zsh-autosuggestions
    sudo -u $SUDO_USER git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /home/$SUDO_USER/.zsh/zsh-syntax-highlighting
    
    exists=$(cat /home/$SUDO_USER/.zshrc | grep -c "zsh-autosuggestions")
    if [[ $exists == 0 ]]; then
        echo "source /home/${SUDO_USER}/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" >> /home/$SUDO_USER/.zshrc
    fi
    
    exists=$(cat /home/$SUDO_USER/.zshrc | grep -c "zsh-syntax-highlighting")
    if [[ $exists == 0 ]]; then
        echo "source /home/${SUDO_USER}/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> /home/$SUDO_USER/.zshrc
    fi
fi

clear
read -p "Install gaming applications [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    sudo -u $SUDO_USER curl -L -o /home/$SUDO_USER/Applications/osu.AppImage https://github.com/ppy/osu/releases/latest/download/osu.AppImage
    cp -f /home/$SUDO_USER/.dotfiles/misc/osu.desktop /home/$SUDO_USER/.local/share/applications
fi

clear

