#!/bin/sh

if [ $EUID != 0 ]
then
    echo "This script requires root, please run as root"
fi

script_dir="/home/$SUDO_USER/.dotfiles/configs/sddm"

cp -rf $script_dir/themes/sugar-candy /usr/share/sddm/themes/sugar-candy
cp -f $script_dir/sddm.conf /etc/sddm.conf
