#!/bin/sh

if [ $EUID != 0 ]
then
    echo "This script requires root, please run as root"
fi

pacman -S qt5-graphicaleffects qt5-quickcontrols2 qt5-svg

cp -r ./themes/sugar-candy /usr/share/sddm/themes/sugar-candy
cp ./sddm.conf /etc/sddm.conf
