#!/bin/bash

if [ $EUID != 0 ]
then
    echo "This script requires root, please run as root"
    exit
fi

echo "Running grub config"
cd $HOME/grub
./install.sh
cd $HOME/.bin

install_essentials

read -p "Would you like to install gaming apps? (Y/n): "
if [[ !($REPLY == 'n' ||  $REPLY == 'N') ]]; then
    install_gaming_apps
fi

read -p "Would you like to install emulators? (Y/n): "
if [[ !($REPLY == 'n' ||  $REPLY == 'N') ]]; then
    install_emulators
fi
