#!/bin/bash

if [ $EUID != 0 ]
then
    echo "This script requires root, please run as root"
    exit
fi

echo "Updating pacman"
pacman -Syy

echo "Installing gaming apps"
pacman -S discord steam ttf-liberation

flatpak install flathub com.stepmania.StepMania
