#!/bin/bash

if [ $EUID != 0 ]
then
	echo "This script requires root, please run as root"
	exit
fi

echo "Updating pacman"
pacman -Syy

echo "Installing required audio packages"
pacman -S wireplumber alsa-utils pavucontrol pipewire pipewire-alsa pipewire-audio pipewire-pulse pipewire-jack
