#!/bin/bash

if [ $EUID != 0 ]
then
    echo "This script requires root, please run as root"
    exit
fi

echo "Updating pacman"
pacman -Syy

echo "Installing essentials"
pacman -S kitty firefox dolphin kate partitionmanager spectacle gwenview vlc unzip git code openssh noto-fonts-emoji flatpak
