#!/bin/sh

clear

if [ $EUID != 0 ]
then
    source $HOME/Scripts/formatting_vars
    echo -e "${ESC_CHAR}${BOLD}$(($RED))${END}You must run this as root"
    exit
fi

echo "Here are the supported environments:"
echo "  1. Hyprland"
echo "  2. KDE Plasma"
read -p "Select which you are using: " environment
if [[ $environment == '1' ]]; then
    echo "Hyprland"
elif [[ $environment == '2' ]]; then
    echo "KDE Plasma"
fi

echo "Installing config files..."
cp -rf /home/$SUDO_USER/Scripts/grub/themes /boot/grub
if [[ $environment == '1' ]]; then
    
elif [[ $environment == '2' ]]; then
    echo "KDE Plasma"
fi


read -p "Install packages? [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    # Fonts
    packages="noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-font-awesome "
    
    # Essentials
    packages+="git base-devel bc unzip cmake npm zsh sddm firefox kitty "

    # Get packages for environment
    if [[ $environment == '1' ]]; then
        echo "Hyprland"
        packages+="hyprpaper waybar brightnessctl mako wofi thunar grim slurp "
    elif [[ $environment == '2' ]]; then
        echo "KDE Plasma"
        packages+="dolphin partitionmanager "
    fi

    # Extra Programming Stuff
    packages+="dotnet-runtime dotnet-sdk "

    pacman -Syy
    clear
    pacman -Sq --needed $packages
fi

# Install yay
clear
read -p "Install yay? [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    sudo -u $SUDO_USER git clone https://aur.archlinux.org/yay.git /home/$SUDO_USER/yay
    (cd /home/$SUDO_USER/yay && sudo -u $SUDO_USER makepkg -si)
    rm -rf /home/$SUDO_USER/yay
fi

# Install zsh
read -p "Install zsh add-ons? [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    sudo -u $SUDO_USER git clone https://github.com/zsh-users/zsh-autosuggestions /home/$SUDO_USER/.zsh/zsh-autosuggestions
    sudo -u $SUDO_USER git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /home/$SUDO_USER/.zsh/zsh-syntax-highlighting
    
    exists=$(cat /home/$SUDO_USER/.zshrc | grep -c "zsh-autosuggestions")
    if [[ $exists == 0 ]]; then
        echo "source /home/${SUDO_USER}/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" >> /home/$SUDO_USER/.zshrc
    fi
    
    exists=$(cat /home/$SUDO_USER/.zshrc | grep -c "zsh-syntax-highlighting")
    if [[ $exists == 0 ]]; then
        echo "source /home/${SUDO_USER}/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> /home/$SUDO_USER/.zshrc
    fi
fi

# Neovim stuff
read -p "Install packer.nvim? [Y/n] "
if [[ $REPLY == '' || $REPLY == 'y' || $REPLY == 'Y' ]]; then
    git clone --depth 1 https://github.com/wbthomason/packer.nvim\
        /home/$SUDO_USER/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

clear

